/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}

import {
  VirtualScrollChangeEvent,
} from './components/virtual-scroll/virtual-scroll';

import {
  VirtualScrollExample as VirtualScrollExample
} from './components/virtual-scroll-example/virtual-scroll-example';

declare global {
  interface HTMLVirtualScrollExampleElement extends VirtualScrollExample, HTMLStencilElement {
  }
  var HTMLVirtualScrollExampleElement: {
    prototype: HTMLVirtualScrollExampleElement;
    new (): HTMLVirtualScrollExampleElement;
  };
  interface HTMLElementTagNameMap {
    "virtual-scroll-example": HTMLVirtualScrollExampleElement;
  }
  interface ElementTagNameMap {
    "virtual-scroll-example": HTMLVirtualScrollExampleElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "virtual-scroll-example": JSXElements.VirtualScrollExampleAttributes;
    }
  }
  namespace JSXElements {
    export interface VirtualScrollExampleAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}


import {
  VirtualScrollComponent as SpVirtualScroll
} from './components/virtual-scroll/virtual-scroll';

declare global {
  interface HTMLSpVirtualScrollElement extends SpVirtualScroll, HTMLStencilElement {
  }
  var HTMLSpVirtualScrollElement: {
    prototype: HTMLSpVirtualScrollElement;
    new (): HTMLSpVirtualScrollElement;
  };
  interface HTMLElementTagNameMap {
    "sp-virtual-scroll": HTMLSpVirtualScrollElement;
  }
  interface ElementTagNameMap {
    "sp-virtual-scroll": HTMLSpVirtualScrollElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "sp-virtual-scroll": JSXElements.SpVirtualScrollAttributes;
    }
  }
  namespace JSXElements {
    export interface SpVirtualScrollAttributes extends HTMLAttributes {
      buffer?: number;
      change?: (event: VirtualScrollChangeEvent) => void;
      end?: (event: VirtualScrollChangeEvent) => void;
      ignoreClass?: string;
      items?: any[];
      parentScroll?: HTMLElement;
      start?: (event: VirtualScrollChangeEvent) => void;
      update?: (list: any[]) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
